### ISSUE TITLE
trash_next fails

### ISSUE THREAD

**Issue by Veldkornet** [xirixiz/Home-Assistant-Sensor-Afvalwijzer#31]
After updating from 3.0.10 to 3.0.11, my log is now filled with errors like the below.

```
2019-12-10 21:25:07 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.trash_next fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 270, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 450, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalwijzer/sensor.py", line 143, in update
    self._state = item['value'].strip()
AttributeError: 'int' object has no attribute 'strip'
```

**Comment by freemann** [comment]
Same over here, log is flooding with errors;
```
Update for sensor.trash_next fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 281, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 461, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalwijzer/sensor.py", line 143, in update
    self._state = item['value'].strip()
AttributeError: 'int' object has no attribute 'strip'
----
22:04 custom_components/afvalwijzer/sensor.py (ERROR) - bericht kwam voor het eerst om 17:27 en verschijnt 540 malen
```
Almost 100 loglines every hour.

**Comment by Mariusthvdb** [comment]
Has been addressed in a new Pr...

You can manually delete the strip from the sensor.py until the Pr is merged

**Comment by freemann** [comment]
That fixed it! thanks!
